project:
  type: website
  output-dir: docs

website:
  title: "USC"
  navbar:
    left:
      - text: "Unstable Slopes Criteria Project"
        href: about.qmd
      - text: "Landslide susceptibility"
        href: index.qmd
      - text: "Coregistration"
        href: Coregistration.qmd

#  sidebar:
#    style: "docked"
#    search: true
#    contents:
#      - text: "Coregistration"
#        href: coregistration.qmd

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true

editor: visual
bibliography: references.bib
