project:
  type: website
  output-dir: docs

website:
  title: "USC"
  navbar:
    search: true
    left:
      - text: "Unstable Slopes Criteria"
        href: index.qmd
      - text: "Landslide Susceptibility"
        href: about.qmd

  sidebar:
    - title: "Landslide Susceptibility"
      style: "docked"
      contents:
      - text: "Introduction"
        href: about.qmd
      - text: "Aligning DEMs: Coregistration"
        href: Coregistration.qmd
      - text: "Identifying landslides"
        href: MappingLandslides.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
bibliography: references.bib
