project:
  type: website
  output-dir: docs

website:
  title: "Unstable Slopes Criteria Project"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Coregistration"
        href: coregistration.qmd
      - about.qmd

  sidebar:
    - title: "Coregistration"
      style: "docked"
      search: true
      contents:
        - Coregistration.qmd

      tools:
        - icon: github
          menu:
            - text: "Source"
              href: https://coregistration.qmd
        - icon: File word fill
          menu:
          - text: "Microsoft Word"
            href: https://docs/coregistration.docx

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

