project:
  type: website
  output-dir: docs

website:
  title: "Unstable Slopes Criteria Project"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Coregistration"
        href: Coregistration.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

